# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
foreground #bebebe
background #121212
selection_foreground #bebebe
selection_background #333333
cursor #eaeaea
cursor_text_color #121212
active_border_color #e68e0d
active_tab_background #e68e0d
color0 #333333
color1 #D35F5F
color2 #FFC107
color3 #b91c1c
color4 #e68e0d
color5 #D35F5F
color6 #bebebe
color7 #bebebe
color8 #8a8a8d
color9 #B91C1C
color10 #FFC107
color11 #b90a0a
color12 #f59e0b
color13 #B91C1C
color14 #eaeaea
color15 #ffffff
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
