# Extra autostart processes
# System dark-mode preference for portal/GSettings-aware apps
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once = gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

# Slow app launch fix -- set systemd vars before app startup
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/background -m fill
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm-app -- rob-monitor-watch
