# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Local shared defaults
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/base-windows.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/tiling.conf

# Persistent runtime toggles written by ~/.local/bin helpers.
#source = ~/.local/state/dotfiles/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = XDG_SESSION_TYPE,wayland

cursor {
  #no_hardware_cursors = true
}
